version: 2.1 # CircleCI version
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: 's3://elementary-circleci/dump.sql'
          to: tmp/dump.sql
      - run: echo pwd
      - run: cat tmp/dump.sql
#      - run: docker-compose up -d
#      - store_artifacts:
#          path: ~/repo/features/fail-screenshots
#      - run:
#          name: Execute test
#          command: bash build.sh
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build